LABELS: list[str] = [
    "hola",
    "buenos_dias",
    "gracias",
    "mucho gusto",
    "mi_nombre_es",
    "cuidate",
    "buenas tardes",
    "buenas noches",
    "como estas",
    "cual es tu nombre",
    "permiso",
    "adios",
    "perdon",
    "otra vez",
    "por favor",
    "duda",
    "nos vemos luego",
    "por que",
    "si",
    "no",
    "talvez",
    "no se",
    "nada",
]
